[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 88
multi_line_output = 3
known_first_party = ["django_starter"]
[tool.djlint]
profile = "django"
ignore = "H030,H031,H006,T002,T003,D018"
